# Lab 7 - TensorFlow

TensorFlow is a popular open-source library for numerical computation and machine learning. It provides a comprehensive, flexible ecosystem of tools, libraries, and community resources that lets researchers push the state-of-the-art in ML, and developers easily build and deploy ML-powered applications.

## Part 1: Getting Started with TensorFlow

#### Install TensorFlow

In [2]:
# Requires the latest pip
! pip install --upgrade pip

# Current stable release for CPU and GPU
! pip install tensorflow

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 22.9 MB/s eta 0:00:00:00:01
  Attempting uninstall: pip
    Found existing installation: pip 23.3.2
    Uninstalling pip-23.3.2:
      Successfully uninstalled pip-23.3.2
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.0/61.0 kB 4.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.4/45.4 kB 2.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 589.8/589.8 MB 481.5 kB/s eta 0:00:0000:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 133.7/133.7 kB 1.9 MB/s eta 0:00:00:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.5/5.5 MB 23.0 MB/s eta 0:00:0000:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 21.2 MB/s eta 0:00:00:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.5/24.5 MB 16.5 MB/s eta 0:00:00:00:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.2/2.2 MB 9.4 MB/s eta 0:00:000:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.2/18.2 MB 8.7 MB/s eta 0:00:00:00:01:00:01
   ━

### Basic Concepts
#### Tensors
The core unit of data in TensorFlow is a tensor. A tensor consists of a set of primitive values shaped into an array of any number of dimensions.

In [3]:
import tensorflow as tf

# Create a tensor
tensor = tf.constant([[1, 2], [3, 4]])
print(tensor)

2024-04-02 19:24:39.743443: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-04-02 19:24:41.525560: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT


tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


2024-04-02 19:25:00.244602: E external/local_xla/xla/stream_executor/cuda/cuda_driver.cc:282] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected


#### Operations
You can perform operations on tensors like addition, multiplication, and matrix operations.

In [4]:
# Addition
tensor_add = tensor + 5
print(tensor_add)

# Multiplication
tensor_mul = tensor * 2
print(tensor_mul)

tf.Tensor(
[[6 7]
 [8 9]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[2 4]
 [6 8]], shape=(2, 2), dtype=int32)


#### Building a Simple Model
TensorFlow makes it easy to build models through layers and models API, typically using the Keras API. Learn more about Keras: https://keras.io/getting_started/

In [5]:
# Define a simple Sequential model
model = tf.keras.Sequential([
    tf.keras.layers.Dense(10, activation='relu', input_shape=(None, 5)),
    tf.keras.layers.Dense(1)
])

model.summary()

model.compile(optimizer='adam', loss='mean_squared_error')

/home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/keras/src/layers/core/dense.py:88: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, None, 10)       │            60 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, None, 1)        │            11 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 71 (284.00 B)

 Trainable params: 71 (284.00 B)

 Non-trainable params: 0 (0.00 B)

1. Find out about layers types in Keras documentation. Briefly explain about the `Dense` layer.
2. What does `model.summary()` show?
3. What does `model.compile` do?
4. What does optimizer do?
5. What is `loss`?

* Layers are the basic building blocks of neural networks in Keras. The Dense layer is one of the most common layers. The Dense layer is a neural network layer that is connected deeply. Each neuron in the Dense layer receives input from all neurons of its previous layer.

* model.summary() is a method that prints a brief overview of the model by showing its layers, output shape, and the number of parameters each layer has.  It also shows the total number of parameters in the model.

* model.compile() is a method that is used to configure the learning process before training the model. It configures a model for training.

* The optimizer adjust the attributes of a neural network such as its weights and learning rate with the purpose of reducing the losses.

* The loss function measures the model's performance. It computes the quantity that a model should seek to minimize during training. The loss function measures the discrespancy between the prediction of the model and the true label.

## Part 2: Implement a Simple TensorFlow Example

Let's build a simple model that learns to add two numbers. Partial codes are provided for you to complete them.

### Task 1: Generate Data
First, we need data to train our model. For simplicity, we you will generate synthetic data.

In [6]:
import numpy as np

# Generate random data
inputs = np.random.random((1000, 2))
sums = np.sum(inputs, axis=1, keepdims=True)

print(inputs[:5], sums[:5])

[[0.20563723 0.6409009 ]
 [0.67326385 0.21949769]
 [0.18593988 0.12944867]
 [0.05782295 0.34906052]
 [0.05164392 0.36205842]] [[0.84653814]
 [0.89276154]
 [0.31538856]
 [0.40688347]
 [0.41370234]]


### Task 2: Build a Model
Now, you need to build a simple model for this task. We would need a model with the following architecture:
1. Number of Layers: 2
2. Layer 1:
      
      2.1 Type: `Dense`
      
      2.2 Neurone: `64`
      
      2.3: Activation Function: `relu`
3. Layer 2:

      3.1 Type: `Dense`
4. Optimizer: `adam`
5. Loss Function: `mean_squared_error`
    

In [7]:
# Define the model
model = tf.keras.Sequential([
    tf.keras.layers.Dense(64, activation='relu'),
    tf.keras.layers.Dense(1)
])

# Compile the model
model.compile(optimizer='adam', loss='mean_squared_error')

### Task 3: Train the Model
With your data and model ready, you can train the model. I suggest training for 10 epochs with batch size of 32. You can change these if you wish.

In [8]:
# Train the model
model.fit(inputs, sums, epochs=10, batch_size=32)

Epoch 1/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 0.9669   
Epoch 2/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.2542 
Epoch 3/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0426  
Epoch 4/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0259 
Epoch 5/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0225 
Epoch 6/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0179 
Epoch 7/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0155 
Epoch 8/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.0132
Epoch 9/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.0102
Epoch 10/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0089 


The loss is reduced over multiple iterations.

### Task 4: Test the Model
Finally, you can test your model with some new data.

In [10]:
# Test data
test_data = np.array([[1, 2], [4, 5]])

# Prediction
predictions = model.predict(test_data)

# Show Predictions
print(predictions)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step
[[2.5728865]
 [7.29515  ]]
